#!/bin/bash

docker image build \
	--build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
	--build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
	--label "org.opencontainers.image.created"=$(date +%Y-%m-%d) \
	--label "org.opencontainers.image.revision"=$SOURCE_COMMIT \
	--label "org.opencontainers.image.version"=$DOCKER_TAG \
	-t $IMAGE_NAME \
	.


